### ISSUE TITLE
Best practices from other PRs

### ISSUE THREAD

**Issue by SoyGema** [SoyGema/contrib_schema#2]
This issue opens tasks that come from reading another PRs that are adapted to the draft. 

- [x] Keep the example **20-30 lines**. _This might enforce using one of the examples, with one word sequence or multiple word sequence. There are currently two of them_ 
- [x]  Follow contributing guidelines including `make style` 

Other
- [x]  eos_token_id inclusion in the example. Unclear if the impact is within the scope of this

**Comment by SoyGema** [comment]
example solution : mimic implementation of [SequenceBiasLogitsProcessor](https://github.com/huggingface/transformers/blob/f1732e1374a082bf8e43bd0e4aa8a2da21a32a21/src/transformers/generation/logits_process.py#L559) and apply it to one word sequence.  The second example shall be removed

**Comment by SoyGema** [comment]
Issues given by PR
- [x] Visited [link](https://app.circleci.com/pipelines/github/huggingface/transformers/68853/workflows/aee86069-783b-4bdb-a50c-9fa474dabb44/jobs/862096?invite=true#step-113-19)

Tried

`pip install git+https://github.com/huggingface/doc-builder `
`doc-builder convert path_to_py_file` ( 'path_to_py_file' is logit_process.py script file )

`git status` doesn´t return any changes

**Comment by SoyGema** [comment]
- [x] Visited [link](https://app.circleci.com/pipelines/github/huggingface/transformers/68853/workflows/aee86069-783b-4bdb-a50c-9fa474dabb44/jobs/862099?invite=true#step-110-4)

Tried

`pip install "black[jupyter]"`
`make style`

Results
```
Overwriting content of src/transformers/generation/logits_process.py.
Cleaned 1 files!
```
However, when pushing all seemed to be up to date

**Comment by nablabits** [comment]
Hey @SoyGema, chances are [this line](https://github.com/huggingface/transformers/pull/25046/files#diff-d23b812af8462833ad280d968f3e6e2ee7558bacfc2716cdde44a07bead5e065R764) is the one is spoiling the party of circleci as the comment should have the `>>>` in front and probably black does not like very much the double `##`. It might also happen that the double empty line in L767 is causing problems :thinking: 

For me it worked adding line by line and then running `make quality`  to see what's the bad guy :upside_down_face: 

Hope it helps :pray:

**Comment by SoyGema** [comment]
Hey @nablabits  !   PR was successfully merged. :)
Thanks for your contrib! See you in the Open
